<?php $k=$data['kpis']; $company=$data['company']; ?>
<?php if(($company['status']??'pending')!=='verified'):?><div class="verification-banner"><?=icon('shield',22)?><div><strong>Cadastro empresarial pendente de verificação</strong><p>Veja exatamente o que falta, envie documentos e acompanhe cada etapa da liberação.</p></div><div class="verification-banner-actions"><span class="status filling"><?=e(['pending'=>'Pendente','rejected'=>'Rejeitado'][$company['status']??'pending']??ucfirst($company['status']??'pending'))?></span><a class="btn btn-primary btn-sm" href="<?=e(url('empresa/verificacao'))?>">Verificar cadastro</a></div></div><?php endif;?><div class="page-head"><div><h1>Olá, <?=e($company['trade_name']??'Empresa')?>! <span>👋</span></h1><p>Aqui está um resumo da sua operação no TurnoPronto.</p></div><div class="date-chip"><?=icon('calendar',18)?> <?=date('01').' – '.date('t').' de '.['','Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'][(int)date('n')].', '.date('Y')?>⌄</div></div>
<div class="kpi-grid four">
  <div class="kpi"><div class="kpi-icon blue"><?=icon('briefcase')?></div><div><small>Vagas abertas</small><strong><?=$k['open']?></strong><span class="trend up">Operação atual</span></div></div>
  <div class="kpi"><div class="kpi-icon blue"><?=icon('calendar')?></div><div><small>Turnos hoje</small><strong><?=$k['today']?></strong><span class="trend up">profissionais necessários</span></div></div>
  <div class="kpi"><div class="kpi-icon green"><?=icon('users')?></div><div><small>Taxa de preenchimento</small><strong><?=$k['fill_rate']?>%</strong><span class="trend up">últimos 30 dias</span></div></div>
  <div class="kpi"><div class="kpi-icon green"><?=icon('wallet')?></div><div><small>Gasto no mês</small><strong><?=money($k['spend'])?></strong><span class="trend up">ledger realizado</span></div></div>
</div>
<div class="dashboard-grid">
  <section class="panel span-main">
    <div class="panel-head"><div><h2>Vagas e turnos em aberto</h2></div><div class="head-actions"><a class="link" href="<?=e(url('empresa/vagas'))?>">Ver todas as vagas →</a><a class="btn btn-primary" href="<?=e(url('empresa/vagas/nova'))?>">+ Nova vaga</a></div></div>
    <div class="table-wrap"><table class="tp-table"><thead><tr><th>Função</th><th>Data</th><th>Horário</th><th>Valor</th><th>Status</th><th>Candidatos</th><th>Ações</th></tr></thead><tbody>
    <?php foreach($data['shifts'] as $s): $status=['published'=>'Publicada','filling'=>'Em preenchimento','confirmed'=>'Confirmada','cancelled'=>'Cancelada','draft'=>'Rascunho'][$s['status']]??ucfirst($s['status']); ?>
      <tr>
        <td><div class="role-cell"><div class="role-thumb"><?=e(mb_strtoupper(mb_substr($s['category_name'],0,1)))?></div><div><strong><?=e($s['category_name'])?></strong><small><?=e($s['title'])?></small></div></div></td>
        <td><strong><?=br_date($s['starts_at'],'d M')?></strong><small><?=date('Y-m-d')===date('Y-m-d',strtotime($s['starts_at']))?'Hoje':date('D',strtotime($s['starts_at']))?></small></td>
        <td><strong><?=date('H:i',strtotime($s['starts_at']))?> – <?=date('H:i',strtotime($s['ends_at']))?></strong><small>(<?=round((strtotime($s['ends_at'])-strtotime($s['starts_at']))/3600)?>h)</small></td>
        <td><strong><?=money($s['shift_value'])?></strong><small>por turno</small></td>
        <td><span class="status <?=e($s['status'])?>"><?=e($status)?></span></td>
        <td class="center"><?=e($s['candidates'])?></td>
        <td><a class="btn btn-soft btn-sm" href="<?=e(url('empresa/vagas/'.$s['id']))?>">Gerenciar</a></td>
      </tr>
    <?php endforeach;?></tbody></table></div>
    <div class="activity"><h3>Atalhos operacionais</h3><div><span class="activity-icon green">✓</span><p>Acompanhe profissionais confirmados e check-ins na área de Escalas.</p><a class="link" href="<?=e(url('empresa/escalas'))?>">Abrir →</a></div><div><span class="activity-icon blue">◎</span><p>Convide profissionais confiáveis diretamente para uma vaga aberta.</p><a class="link" href="<?=e(url('empresa/profissionais'))?>">Profissionais →</a></div><div><span class="activity-icon purple">▣</span><p>Consulte custos realizados e valores comprometidos.</p><a class="link" href="<?=e(url('empresa/financeiro'))?>">Financeiro →</a></div></div>
  </section>
  <aside class="right-stack">
    <section class="panel compact"><div class="panel-head"><h3>Sua localização</h3><?php if(!empty($company['maps_url'])):?><span class="muted">Abrir mapa ↗</span><?php endif;?></div><?php if(!empty($company['maps_url'])):?><a class="location-card location-card-link" href="<?=e($company['maps_url'])?>" target="_blank" rel="noopener noreferrer" aria-label="Abrir localização de <?=e($company['trade_name']??'Empresa')?> no Google Maps"><?php else:?><div class="location-card"><?php endif;?><div class="loc-pin"><?=icon('map',22)?></div><div><strong><?=e($company['trade_name']??'Empresa')?></strong><p><?=e($company['address']??'Endereço não informado')?><br><?=e(($company['city']??'').' - '.($company['state']??''))?></p><span class="muted"><?=!empty($company['maps_url'])?'Clique para abrir no Google Maps':'Adicione o link do Maps em Minha conta'?></span></div><div class="mini-map"><span><?=e($company['state']??'BR')?></span><i></i></div><?php if(!empty($company['maps_url'])):?></a><?php else:?></div><?php endif;?></section>
    <section class="panel compact"><div class="panel-head"><h3>Profissionais sugeridos</h3><a class="link" href="<?=e(url('empresa/profissionais'))?>">Ver todos →</a></div><?php foreach($data['professionals'] as $p):?><div class="suggested"><div class="avatar-md"><?=e(mb_strtoupper(mb_substr($p['name'],0,1)))?></div><div class="grow"><strong><?=e($p['name'])?></strong><div class="stars">★ <?=number_format((float)$p['rating'],1,',','.')?> <span>(<?=$p['completed_shifts']?>)</span></div><div class="tags"><span><?=e($p['headline']?:'Profissional')?></span></div></div><div><span class="presence"><?=round($p['attendance_score'])?>% presença</span><a class="mini-btn" href="<?=e(url('empresa/profissionais'))?>">Convidar</a></div></div><?php endforeach;?></section>
    <section class="panel compact"><div class="panel-head"><h3>Próximos turnos</h3><a class="link" href="<?=e(url('empresa/escalas'))?>">Ver agenda →</a></div><?php foreach(array_slice($data['shifts'],0,3) as $s):?><div class="upcoming"><div class="date-box"><strong><?=date('d',strtotime($s['starts_at']))?></strong><small><?=strtoupper(date('M',strtotime($s['starts_at'])))?></small></div><div><strong><?=e($s['category_name'])?></strong><small><?=date('H:i',strtotime($s['starts_at']))?> – <?=date('H:i',strtotime($s['ends_at']))?> · <?=e($s['title'])?></small></div><span class="status published"><?=date('d/m',strtotime($s['starts_at']))?></span></div><?php endforeach;?></section>
  </aside>
</div>
