<?php
$p=$data['profile'];
$k=$data['kpis'];
$onboarding=$data['onboarding'];
$displayName=trim((string)($p['name']??$user['name']??''));
$firstName=$displayName!=='' ? explode(' ',$displayName)[0] : 'Profissional';
$hasCompanyFeedback=(int)($k['company_feedback_count']??0)>0;
$nextPayout=(float)($k['next_payout']??0);
?>
<?php if(!$onboarding['profile_verified']):?>
  <div class="verification-banner professional-onboarding-banner">
    <?=icon($onboarding['identity_submitted']?'clock':'shield',22)?>
    <div>
      <strong><?=$onboarding['identity_submitted']?'Identidade em análise':($onboarding['application_ready']?'Candidaturas liberadas':'Perfil em construção')?></strong>
      <p><?=$onboarding['identity_submitted']
        ?'Seu documento foi enviado. A confirmação do turno será liberada após a validação da identidade.'
        :($onboarding['application_ready']
          ?'Você já pode se candidatar. Complete identidade e endereço antes de ser confirmado para trabalhar.'
          :'Você pode explorar oportunidades. Os dados essenciais serão solicitados quando você se candidatar pela primeira vez.')?></p>
    </div>
    <div class="verification-banner-actions">
      <span class="status filling"><?=$onboarding['progress']?>% completo</span>
      <a class="btn btn-primary btn-sm" href="<?=e(url('profissional/completar?step='.$onboarding['next_step']))?>"><?=$onboarding['identity_submitted']?'Ver verificação':'Completar verificação'?></a>
    </div>
  </div>
<?php endif;?><div class="page-head"><div><h1>Olá, <?=e($firstName)?>! <span>👋</span></h1><p>Aqui está o seu resumo de hoje. Vamos para mais um grande dia?</p></div><div class="date-chip"><?=icon('calendar',18)?> <?=strftime('%A, %d de %B de %Y')?>⌄</div></div>
<div class="pro-layout"><div class="pro-main">
<div class="kpi-grid four">
 <div class="kpi"><div class="kpi-icon blue"><?=icon('calendar')?></div><div><small>Turnos esta semana</small><strong><?=$k['week']?></strong><span class="trend up">↑ +2 em relação à semana anterior</span></div></div>
 <div class="kpi"><div class="kpi-icon green"><?=icon('wallet')?></div><div><small>Ganhos do mês</small><strong><?=money($k['earnings'])?></strong><span class="trend up">↑ 18% em relação ao mês anterior</span></div></div>
 <div class="kpi"><div class="kpi-icon green"><?=icon('shield')?></div><div><small>Confiabilidade</small><strong><?=$hasCompanyFeedback?$k['reliability'].'%':'—'?></strong><span><?=$hasCompanyFeedback?'Baseada nos retornos das empresas':'Aguardando primeira avaliação da empresa'?></span></div></div>
 <div class="kpi"><div class="kpi-icon blue"><?=icon('clock')?></div><div><small>Pontualidade</small><strong><?=$hasCompanyFeedback?$k['punctuality'].'%':'—'?></strong><span><?=$hasCompanyFeedback?'Média das avaliações operacionais':'Será calculada após o primeiro retorno'?></span></div></div>
</div>
<section class="panel" data-opportunity-location><div class="panel-head"><div><h2>Oportunidades próximas</h2><p>Turnos disponíveis que combinam com o seu perfil.</p><small class="location-status" data-location-status>Calculando distância pela localização do navegador…</small></div><a class="link" href="<?=e(url('profissional/oportunidades'))?>">Ver todas as oportunidades →</a></div>
<div class="opportunity-list"><?php foreach($data['opportunities'] as $s):?><div class="opportunity-row" data-opportunity-row data-shift-lat="<?=e((string)($s['latitude']??''))?>" data-shift-lng="<?=e((string)($s['longitude']??''))?>" data-shift-address="<?=e((string)($s['address']??''))?>" data-shift-city="<?=e((string)($s['city']??''))?>" data-shift-state="<?=e((string)($s['state']??''))?>" data-shift-start="<?=e((string)($s['starts_at']??''))?>"><div class="venue-thumb"><?=e(mb_strtoupper(mb_substr($s['category_name'],0,1)))?></div><div class="opp-role"><strong><?=e($s['category_name'])?></strong><span><?=e($s['company_name'])?></span><small><?=icon('map',13)?> <?=e($s['city'].' – '.$s['state'])?></small></div><div class="opp-meta"><?=icon('calendar',16)?><div><strong><?=br_date($s['starts_at'],'D, d M')?></strong></div></div><div class="opp-meta"><?=icon('clock',16)?><div><strong><?=date('H:i',strtotime($s['starts_at']))?> – <?=date('H:i',strtotime($s['ends_at']))?></strong><small>(<?=round($s['duration_minutes']/60)?>h)</small></div></div><div class="opp-value"><strong><?=money($s['shift_value'])?></strong><small>por turno</small></div><div class="opp-distance"><?=icon('map',17)?><div><strong data-opportunity-distance>Calculando…</strong><small><?=e($s['city'].' - '.$s['state'])?></small></div></div><div class="opp-actions"><a class="btn btn-soft" href="<?=e(url('profissional/vagas/'.$s['id']))?>">Ver detalhes</a><form method="post" action="<?=e(url('profissional/vagas/'.$s['id'].'/aceitar'))?>"><?=csrf_field()?><button class="btn btn-primary"><?=$onboarding['can_apply']?($onboarding['profile_verified']&&($s['acceptance_mode']??'automatic')==='automatic'?'Aceitar':'Candidatar-se'):'Completar perfil'?></button></form></div></div><?php endforeach;?></div></section>
<section class="panel"><div class="panel-head"><div><h2>Meus próximos turnos</h2><p>Seus turnos confirmados. Boa sorte!</p></div><a class="link" href="<?=e(url('profissional/agenda'))?>">Ver minha agenda completa →</a></div><div class="table-wrap"><table class="tp-table"><thead><tr><th>Data</th><th>Horário</th><th>Função</th><th>Local</th><th>Valor</th><th>Status</th><th>Ações</th></tr></thead><tbody><?php foreach($data['assignments'] as $a):?><tr><td><div class="date-box inline"><strong><?=date('d',strtotime($a['starts_at']))?></strong><small><?=strtoupper(date('M',strtotime($a['starts_at'])))?></small></div></td><td><strong><?=date('H:i',strtotime($a['starts_at']))?> – <?=date('H:i',strtotime($a['ends_at']))?></strong><small>(<?=round((strtotime($a['ends_at'])-strtotime($a['starts_at']))/3600)?>h)</small></td><td><strong><?=e($a['category_name'])?></strong><small><?=e($a['title'])?></small></td><td><strong><?=e($a['company_name'])?></strong><small><?=e($a['city'].' – '.$a['state'])?></small></td><td><strong><?=money($a['agreed_value'])?></strong><small>por turno</small></td><td><span class="status <?=$a['status']==='completed'?'published':'filling'?>"><?=e(ucfirst(str_replace('_',' ',$a['status'])))?></span></td><td><a class="btn btn-soft btn-sm" href="<?=e(url('profissional/turno/'.$a['id']))?>">Ver detalhes</a></td></tr><?php endforeach;?></tbody></table></div></section>
</div>
<aside class="pro-side right-stack"><section class="panel profile-card"><div class="profile-top"><div class="avatar-xl"><?=e(mb_strtoupper(mb_substr($displayName?:'P',0,1)))?></div><span class="score-badge"><?=icon('shield',18)?><b>Confiabilidade<br><?=$hasCompanyFeedback?$k['reliability'].'%':'—'?></b></span></div><h2><?=e($displayName?:'Profissional TurnoPronto')?></h2><p><?=e($p['headline'])?></p><small><?=icon('map',14)?> <?=e(trim((string)($p['city']??''))!==''?(($p['city']??'').' – '.($p['state']??'')):'Localização ainda não informada')?></small><div class="profile-metrics"><div><?=icon('users',21)?><b><?=$hasCompanyFeedback?round($p['attendance_score']).'%':'—'?></b><span>presença</span></div><div><?=icon('clock',21)?><b><?=$hasCompanyFeedback?round($p['punctuality_score']).'%':'—'?></b><span>pontualidade</span></div></div></section>
<section class="panel compact"><div class="panel-head"><h3>Documentos</h3><a class="link" href="<?=e(url('profissional/documentos'))?>">Ver todos →</a></div><?php if(!$data['documents']):?><div class="mini-empty">Nenhum documento enviado ainda.</div><?php endif;?><?php foreach($data['documents'] as $d):?><div class="doc-row"><?=icon('file',17)?><span><?=e($d['label'])?></span><b class="<?=e($d['status']==='verified'?'verified':'pending')?>">● <?=e($d['status']==='verified'?'Verificado':($d['status']==='rejected'?'Rejeitado':'Em análise'))?></b></div><?php endforeach;?></section>
<section class="panel compact payout"><div class="panel-head"><h3>Próximo repasse</h3><a class="link" href="<?=e(url('profissional/ganhos'))?>">Ver meus ganhos →</a></div><strong class="big-money"><?=money($nextPayout)?></strong><p><?=$nextPayout>0?'Valor já disponível para o próximo processamento.':'Nenhum valor pendente. O saldo aparece após concluir um turno.'?></p></section></aside></div>
